puns = ['A mexican magician was doing a magic trick. He said, Uno, Dos, and he disappeared without a trace',
    'About a month before he died, my uncle had his back covered in lard. After that, he went down hill fast',
    'eBay is so useless. I tried to look up lighters and all they had was 13,749 matches',
    'R.I.P boiled water. You will be mist',
    'How did I escape Iraq? Iran.',
    'I saw an ad for burial plots, and thought to myself this is the last thing I need',
    "I couldn't quite remember how to throw a boomerang, but eventually, it came back to me",
    "I'm glad I know sign language, it's pretty handy",
    "I bought a dictionary and when I got home I realized all the pages were blank; I have no words for how angry I am",
    "A courtroom artist was arrested today for an unknown reason, the details are sketchy",
    "When I lose the TV controller, it's always hidden in some remote destination",
    "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
    "To write with a broken pencil is pointless",
    "A book just fell on my head. I can only blame myshelf",
    "I am on a seafood diet. Every time I see food, I eat it",
    "Police have arrested the World tongue-twister Champion. I imagine he'll be given a tough sentence",
    "What do you call a priest that becomes a lawyer? A father in law",
    "I'm reading a horror story in Braille. Something bad is about to happen. I can feel it",
    "How did Jesus' crucifixion save us? It's 'cause he nailed it!",
    "Cleaning mirrors is a job I could really see myself doing",
    "I hate insects puns, they really bug me",
    "How do trees access the internet? They log in",
    "I overdosed on Viagra once. The hardest day of my life",
    "How does Moses make his tea? Hebrews it",
    "My Gram now does more than a thousand damage. It is now called KiloGram.",
    "I was going to share a vegetable joke but it's corny",
    "Why did the picture end up in jail? It was framed",
    "What do you call a Russian procrastinator? Putoff",
    "Have you ever had sex while camping? It's fucking intents",
    "Is it good or bad if your vacuum sucks?",
    "How do you make a fire with two sticks? Make sure one of them is a match",
    "What did the tree say to autumn? Leaf me alone",
    "Electricity is dangerous. Shocking, ain't it?",
    "Will glass coffins be a success? Remains to be seen",
    "Sang the rainbow song in front of a police officer, got arrested for colourful language",
    "I don't trust stairs. They are always up to something",
    "Don't trust atoms, they make up everything",
    "Thanks for explaining the word 'many' to me, it means a lot",
    "Most people are shocked when they find out how bad I am as an electrician",

];
